# Generated by Django 3.1.7 on 2021-03-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.CharField(max_length=2000, verbose_name='Description')),
                ('due_date', models.DateField(null=True, verbose_name='Due date')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Is closed')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.CharField(max_length=2000, verbose_name='Description')),
                ('start', models.DateTimeField(null=True, verbose_name='Start date')),
                ('end', models.DateTimeField(null=True, verbose_name='End date')),
                ('status', models.CharField(choices=[('new', 'New'), ('in progress', 'In Progress'), ('done', 'Done'), ('closed', 'Closed')], default='new', max_length=20, verbose_name='Status')),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee', to='employees.employee', verbose_name='Assignee')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='employees.employee', verbose_name='Author')),
            ],
        ),
    ]
