# Generated by Django 3.1.7 on 2021-03-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "Comment", "verbose_name_plural": "Comments"},
        ),
    ]
