# Generated by Django 3.1.7 on 2021-03-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_auto_20210322_0732"),
        ("projects", "0008_auto_20210321_1025"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="documents",
            field=models.ManyToManyField(
                to="documents.Document", verbose_name="Documents"
            ),
        ),
    ]
