version: "3.9"

services:
  redis:
    image: library/redis:6.2.1-alpine
    ports:
    - 6380:6379

  memcached:
    image: library/memcached:1.6.9-alpine
    ports:
    - 11214:11211

  postgres:
    image: library/postgres:13.2-alpine
    env_file:
      - .env
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
    - 5434:5432
    healthcheck:
      test: pg_isready -U taskcamp
      interval: 10s
      timeout: 5s
      retries: 3


  rabbitmq:
    image: library/rabbitmq:3.8.14-management-alpine
    env_file:
      - .env
    ports:
    - 15673:15672
    - 5673:5672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 3

  mailcatcher:
    image: iliadmitriev/mailcatcher
    ports:
    - 1080:1080
    - 1025:1025

  uwsgi:
    build:
      context: ./
      dockerfile: Dockerfile
    image: taskcamp-django
    env_file:
      - .env
    ports:
    - 8000:8000
    volumes:
      - type: bind
        source: ./media
        target: /app/media
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

  celery:
    build:
      context: ./
      dockerfile: Dockerfile
    image: taskcamp-django
    env_file:
      - .env
    command: celery -A worker worker -c 20
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

volumes:
  pgdata: {}
