version: "3.9"

services:
  redis:
    image: redis:6.2-alpine3.14
    hostname: taskcamp-redis
    networks:
      - taskcamp
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  memcached:
    image: memcached:1.6.10-alpine3.14
    hostname: taskcamp-memcached
    networks:
      - taskcamp

  postgres:
    image: postgres:13.4-alpine3.14
    hostname: taskcamp-postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - taskcamp
    healthcheck:
      test: pg_isready -U taskcamp
      interval: 10s
      timeout: 5s
      retries: 3


  rabbitmq:
    image: rabbitmq:3.8.14-management-alpine
    hostname: taskcamp-rabbitmq
    env_file:
      - .env
    networks:
      - taskcamp
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 3

  mail:
    image: iliadmitriev/mailcatcher
    hostname: taskcamp-mail
    networks:
      - taskcamp
    ports:
    - "1080:1080"

  django:
    build:
      context: ./
      dockerfile: Dockerfile
    image: taskcamp-django
    hostname: taskcamp-django
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - taskcamp
    volumes:
      - type: bind
        source: ./media
        target: /app/media
    depends_on:
      - rabbitmq
      - postgres

  celery:
    build:
      context: ./
      dockerfile: Dockerfile
    image: taskcamp-django
    hostname: taskcamp-celery
    env_file:
      - .env
    networks:
      - taskcamp
    command: celery -A worker worker -c 8
    depends_on:
      - rabbitmq
      - postgres

volumes:
  pgdata: {}

networks:
  taskcamp:
    name: taskcamp-network