[tool.poetry]
name = "taskcamp"
version = "0.1.0"
description = "simple project management tool powered by Django Framework"
authors = ["Ilia Dmitriev <ilia.dmitriev@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
Django = "^4.1"
celery = "^5.2.7"
uWSGI = "^2.0.20"
psycopg2 = "^2.9.3"
redis = "^4.3.4"
Markdown = "^3.4.1"
pymemcache = "^3.5.2"
tzdata = "^2022.4"

[tool.poetry.dev-dependencies]
flake8-isort = "^4.2.0"
flake8-quotes = "^3.3.1"
flake8-docstrings = "^1.6.0"
flake8-annotations = "^2.9.1"
flake8-comprehensions = "^3.10.0"
black = "^22.8.0"
flake8-polyfill = "^1.0.2"
pep8-naming = "^0.13.2"
pdoc3 = "^0.10.0"
coverage = "^6.5.0"
django-debug-toolbar = "^3.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
