# Generated by Django 3.1.7 on 2021-03-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(max_length=50, verbose_name="Firstname"),
                ),
                ("surname", models.CharField(max_length=50, verbose_name="Surname")),
                ("email", models.EmailField(max_length=100, verbose_name="Email")),
                ("birthdate", models.DateField(verbose_name="Birthdate")),
            ],
        ),
    ]
