# Generated by Django 3.1.7 on 2021-03-22 07:18

from django.db import migrations, models
import documents.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Date and time uploaded')),
                ('document', models.FileField(upload_to=documents.helpers.document_upload_path, verbose_name='Document')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
