apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mailcatcher
  name: mailcatcher
spec:
  containers:
  - image: iliadmitriev/mailcatcher
    imagePullPolicy: Always
    name: mailcatcher
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    livenessProbe:
      tcpSocket:
        port: 1025
      timeoutSeconds: 5
      initialDelaySeconds: 5
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - all
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: mailcatcher
  name: mailcatcher-node-port
spec:
  ports:
  - port: 1080
    protocol: TCP
    targetPort: 1080
  selector:
    run: mailcatcher
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: mailcatcher
  name: mailcatcher
spec:
  ports:
  - name: mail-web
    port: 1080
    protocol: TCP
    targetPort: 1080
  - name: mail-smtp
    port: 1025
    protocol: TCP
    targetPort: 1025
  selector:
    run: mailcatcher
  type: NodePort
