apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mailcatcher
  name: mailcatcher
spec:
  containers:
  - image: iliadmitriev/mailcatcher
    name: mailcatcher
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: mailcatcher
  name: mailcatcher-node-port
spec:
  ports:
  - port: 1080
    protocol: TCP
    targetPort: 1080
  selector:
    run: mailcatcher
  type: NodePort
