apiVersion: v1
kind: Pod
metadata:
  labels:
    run: memcached
  name: memcached
spec:
  containers:
  - name: memcached
    image: memcached:1.6.10-alpine3.14
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    livenessProbe:
      tcpSocket:
        port: 11211
      timeoutSeconds: 5
      initialDelaySeconds: 5
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 11211
      runAsGroup: 11211
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - all
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: memcached
  name: memcached
spec:
  ports:
  - port: 11211
    protocol: TCP
    targetPort: 11211
  selector:
    run: memcached
