apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  labels:
    app: rmq-taskcamp
  annotations:
    some: annotation
  name: rmq-taskcamp
spec:
  replicas: 2
  image: rabbitmq:3.9.1-management-alpine
  rabbitmq:
    additionalConfig: |
      default_user = guest 
      default_pass = guest
      default_vhost = guest
      default_user_tags.administrator = true
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 500m
      memory: 500Mi
  persistence:
    storage: 2Gi
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            securityContext: {}
            initContainers:
            - name: setup-container
              securityContext: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    some: annotation
  labels:
    app: rmq-taskcamp
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: rmq-taskcamp
    app.kubernetes.io/part-of: rabbitmq
  name: rmq-management-nodeport
spec:
  ports:
  - name: management
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app.kubernetes.io/name: rmq-taskcamp
  type: NodePort
