apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: taskcamp
  name: taskcamp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: taskcamp
  template:
    metadata:
      labels:
        app: taskcamp
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
        runAsGroup: 1000
        fsGroupChangePolicy: Always
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: ['sh', '-c', "chown -R 1000:1000 /app/media"]
          securityContext:
            runAsGroup: 0
            runAsUser: 0
          volumeMounts:
          - name: media
            mountPath: /app/media
      containers:
      - image: iliadmitriev/taskcamp
        imagePullPolicy: Always
        name: taskcamp
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 1000m
            memory: 250Mi
          limits:
            cpu: 2000m
            memory: 500Mi
        envFrom:
        - secretRef:
            name: taskcamp-secret
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /status-page/
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
          runAsGroup: 1000
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
              - all
        volumeMounts:
          - mountPath: /app/media
            name: media
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: taskcamp-media
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: taskcamp-celery
  name: taskcamp-celery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskcamp-celery
  template:
    metadata:
      labels:
        app: taskcamp-celery
    spec:
      containers:
      - image: iliadmitriev/taskcamp
        imagePullPolicy: Always
        name: taskcamp-celery
        command: ["python3"]
        args: ["-m", "celery", "-A", "worker", "worker"]
        livenessProbe:
          exec:
            command: ["python3", "-m", "celery", "-A", "worker", "status"]
          initialDelaySeconds: 3
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
          runAsGroup: 1000
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
              - all
        resources:
          requests:
            cpu: 1000m
            memory: 250Mi
          limits:
            cpu: 2000m
            memory: 500Mi
        envFrom:
        - secretRef:
            name: taskcamp-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: taskcamp
  name: taskcamp
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: taskcamp
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taskcamp-media
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
